---
# tasks file for mysqld_exporter
- name: Downloading and unarchiving.
  unarchive:
    src: "{{ url }}"
    dest: "{{ path }}"
    remote_src: yes

- name: creating .my.cnf in users home directory
  template:
    src: .my.cnf
    dest: ~/
    mode: 0755
    owner: root

- name: Exporting Environment Variables
  lineinfile:
    path: /root/.bashrc
    insertafter: "EOF"
    line: "export DATA_SOURCE_NAME='root:{{ password }}@(localhost:3306)/'"

- name: Executing Script
  shell: source /root/.bashrc
  args:
    executable: /bin/bash

- name: Creating service for mysqld_exporter.
  template:
    src: mysqld_exporter.service
    dest: /etc/systemd/system/
    mode: 0755
    owner: root
  notify: daemon_reload
     
- name: Enabling the mysql_exporter service
  service:
    name: mysqld_exporter
    enabled: yes

- name: Starting the mysqld_exporter service
  service:
    name: mysqld_exporter
    state: started

