---
# tasks file for collectd_exporter
- name: Downloading and unarchiving.
  unarchive:
    src: "{{ url }}"
    dest: "{{ path }}"
    remote_src: yes

- name: Creating service for collectd_exporter.
  template:
    src: collectd_exporter.service
    dest: /etc/systemd/system/
    mode: 0755
    owner: root
  notify: daemon_reload
     
- name: Enabling the collectd_exporter service
  service:
    name: collectd_exporter
    enabled: yes

- name: Starting the clooectd_exporter service
  service:
    name: collectd_exporter
    state: started
...

